boostorg/compute

- include/boost/compute/memory_object.hpp
- test/test_buffer.cpp
Added a template based register destructor callback function to the memory_object class.
> Register destructor callback is now templated

- include/boost/compute/async/wait_guard.hpp
The noncopyable header was missing.
> Fixed missing header

- include/boost/compute/algorithm/detail/radix_sort.hpp
* pragma khr_fp64 was not being enabled for key type double
> BUGFIX enable double for key type in radix sort by key

- include/boost/compute/kernel.hpp
Please correct me if I am wrong, but I don't see a reason for `kernel::get_work_group_info()` to be non-const.
> kernel::get_work_group_info() should be const

- include/boost/compute/detail/meta_kernel.hpp
- include/boost/compute/detail/sha1.hpp
- include/boost/compute/program.hpp
This gets rid of temporary strings allocation in implementation of offline cache. See #440, #441 for details.
> Offline cache optimization

- include/boost/compute/iterator/strided_iterator.hpp
- test/CMakeLists.txt
- test/test_strided_iterator.cpp
This addresses issue #121.
I've added ```strided_iterator``` adaptor which - as requested - skips over multiple elements each time it is incremented. It's called strided_iterator to match corresponding iterator in the Boost.Range library (see [boost/range/adaptor/strided.hpp](http://www.boost.org/doc/libs/1_58_0/boost/range/adaptor/strided.hpp)). Tests included. 
I've also included function ```make_strided_iterator_end()```. It may be useful. What do you think about it?
@kylelutz, thank you for providing your code. It was helpful.
> Add strided_iterator class (skip_iterator) #121

- CMakeLists.txt
- cmake/FindBolt.cmake
- perf/CMakeLists.txt
- perf/perf.py
- perf/perf_bolt_accumulate.cpp
- perf/perf_bolt_count.cpp
- perf/perf_bolt_exclusive_scan.cpp
- perf/perf_bolt_fill.cpp
- perf/perf_bolt_inner_product.cpp
- perf/perf_bolt_max_element.cpp
- perf/perf_bolt_merge.cpp
- perf/perf_bolt_partial_sum.cpp
- perf/perf_bolt_saxpy.cpp
- perf/perf_bolt_sort.cpp
- perf/perf_thrust_exclusive_scan.cu
- perf/perfdoc.py
This addresses issue https://github.com/kylelutz/compute/issues/220.
I've added:
* BOOST_COMPUTE_HAVE_BOLT option
* FindBolt.cmake cmake module from https://github.com/HSA-Libraries/Bolt
* Bolt perf tests (10):
* bolt_accumulate (reduce)
* bolt_count
* bolt_exclusive_scan
* bolt_fill
* bolt_inner_product
* bolt_max_element
* bolt_merge
* bolt_partial_sum (inclusive scan)
* bolt_saxpy (transform)
* bolt_sort
* Bolt perf tests in python benchmarking script perf.py
* Missing copyright and license info in one perf test
Bolt requires C++11, so performance tests for Bolt are build only if BOOST_COMPUTE_USE_CPP11 option is enabled. if BOOST_COMPUTE_HAVE_BOLT option is on and BOOST_COMPUTE_USE_CPP11 is off, warning message is printed.
If you're trying to test this PR and have problems with …
> Performance tests for AMD's Bolt library

- include/boost/compute/container/valarray.hpp
- include/boost/compute/functional/operator.hpp
- test/test_valarray.cpp
This addresses issue https://github.com/boostorg/compute/issues/381.
I've implemented all missing valarray operators (see [valarray operators](http://www.cplusplus.com/reference/valarray/valarray/operators/)) and added tests for them.
Implemented operators work only for default context (queue) and are asynchronous.
Note that in OpenCL it's impossible to create memory buffer with bool type and because of that ```valarray<char>``` is used  as a return type for comparison and logical operators instead of ```valarray<bool>```.
> Missing valarray operators

- include/boost/compute/random/uniform_int_distribution.hpp
This fixes the default values for the uniform_int_distribution
constructor to match std::uniform_int_distribution.
> Fix default values in uniform_int_distribution constructor

- test/test_transform_if.cpp
This fixes the transform_if() test to copy to a separate output
vector as in-place operation is not supported.
> Fix transform_if() test

- include/boost/compute/algorithm/detail/find_extrema.hpp
- include/boost/compute/algorithm/detail/find_extrema_reduce.hpp
- perf/CMakeLists.txt
- perf/perf_stl_max_element.cpp
This adds ```find_extrema_reduce``` function and change ```find_extrema``` function to use it if there is enough local memory on device to perform an efficient parallel reduction. If there is not, ```find_extema_with_atomics``` is used (just like it was).
```find_extrema_reduce``` and ```find_extema_with_atomics``` get the same time results in ```perf_max_element``` benchmark. For vectors with 134217728 elements the difference is visible. 
master branch:
```
=== max_element with stl ===
size,time (ms)
2,0.000231
4,0.000260
8,0.000286
16,0.000299
32,0.000312
64,0.000364
128,0.000421
256,0.000519
512,0.000779
1024,0.001274
2048,0.002192
4096,0.004097
8192,0.007887
16384,0.015551
32768,0.030970
65536,0.061633
131072,0.123388
262144,0.251553
524288,0.506069
1048576,1.010500
2097152,2.298420 …
```
> find_extrema based on parallel reduction

- test/test_fill.cpp
This addresses issue https://github.com/boostorg/compute/issues/219.
I've added tests for `fill()` and `fill_n()` functions for every OpenCL built-in type using  `BOOST_AUTO_TEST_CASE_TEMPLATE`.
> Add fill() and fill_n() tests for every built-in type

- CMakeLists.txt
I am packaging BoostCompute for Gentoo Linux. Normally on Linux systems cmake configurations go to /usr/lib/cmake, while Find*.cmake modules go to /usr/share/cmale/Modules. I assume the installation path should be changed.
> Install BoostComputeConfig.cmake to lib/cmake/BoostCompute

- include/boost/compute/algorithm/detail/scan.hpp
- include/boost/compute/algorithm/detail/scan_on_cpu.hpp
- include/boost/compute/algorithm/detail/scan_on_gpu.hpp
- include/boost/compute/algorithm/exclusive_scan.hpp
- include/boost/compute/algorithm/inclusive_scan.hpp
- include/boost/compute/types/fundamental.hpp
- test/test_scan.cpp
- test/test_types.cpp
This addresses issue https://github.com/boostorg/compute/issues/374.
Now in inclusive and exclusive scan custom associative binary operator can be used instead of default addition operator. For exclusive scan also initial value can be set. 
I've updated docs for inclusive and exclusive scan.
I've also added single argument constructor for vector types (``int2(1) == int2(1,1) == vector_type<int,2>(1)``, ``int4(4) = int4(4, 4, 4, 4)  == vector_type<int,4>(1)``, etc.).
> Support for custom functions in inclusive and exclusive scan

- cmake/FindOpenCL.cmake
Hello
As CUDA is not always installed at /usr/lib64/nvidia it is reasonable to scan CUDADIR environment variable
Regards,
Tomek
> Added CUDADIR to scaning paths

- include/boost/compute/algorithm/detail/merge_sort_on_cpu.hpp
- include/boost/compute/algorithm/sort.hpp
- include/boost/compute/algorithm/stable_sort.hpp
- test/test_sort.cpp
This adds CPU-targeted stable merge sort (bottom-up version). It does not use local memory, so it should work on OS X without problems.
Algorithms works in to steps:
1. Insertion sort for the blocks of 64 values is performed (the size of block is customizable).
2. Sorted blocks are merged.
It has O(n) space complexity.
If input has 512 elements of less insertion sort is performed. Merge sort outperforms std::sort() on my AMD Phenom(tm) II X3 710 when input has more than 65536, but I think it should work better on a CPU with more cores.
In order to test this algorithm I recommend running `export BOOST_COMPUTE_DEFAULT_DEVICE_TYPE=CPU` (or however it's done in you shell) before executing `perf_sort` or `test_sort`. This environment variable makes your CPU the default device for …
> CPU-targeted merge sort

- test/test_accumulate.cpp
This fixes violation of the Boost min/max guidelines I missed in https://github.com/boostorg/compute/pull/480. 
There is new Boost Inspection Report (28.07): http://boost.cowic.de/rc/docs-inspect-develop.html#compute.
> Fix overlooked violation of the Boost min/max guidelines

- include/boost/compute/algorithm/detail/merge_with_merge_path.hpp
- include/boost/compute/algorithm/merge.hpp
- perf/perf_merge.cpp
- perf/perf_stl_merge.cpp
It turns out that for relatively small serial merge algorithm outperforms merge with merge path, so I added `serial_merge_threshold` (what is considered "small" depends on used device). When input size is less or equal to `serial_merge_threshold` serial merge is used; otherwise merge with merge path is used. 
I thought I would have had to implement the serial merge, but it had been already implemented, just not used.
Default `serial_merge_threshold` threshold value depends on device type - for CPUs it's 32768, for GPUs only 2048 (these values were obtained experimentally and are customizable). 
Benchmarks (thresholds are marked by `<---- `):
std::merge():
```
=== merge with stl ===
size,time (ms)
2,0.000229
4,0.000233
8,0.000236
16,0.000250
32,0.000279
64,0.000394
128,0.000617 …
```
> Using serial merge in merge() for small inputs

- include/boost/compute/algorithm/detail/merge_sort_on_cpu.hpp
- include/boost/compute/algorithm/sort_by_key.hpp
I modified CPU-targeted merge sort (see https://github.com/boostorg/compute/pull/486), so it can also perform sorting by key.
I also restricted usage of `radix_sort` in `sort_by_key.hpp` to only these situations when type of the keys is "radix sortable" (like it's done in [`sort.hpp`](https://github.com/boostorg/compute/blob/develop/include/boost/compute/algorithm/sort.hpp)).
> CPU-targeted merge sort adapted for sorting by key

- include/boost/compute/algorithm/reduce.hpp
There is a bug which causes using `reduce_on_gpu` whenever reduction function is `plus<T>`, even if device is not a GPU. Now for CPU devices `serial_reduce` is always used. 
This should fix https://github.com/boostorg/compute/issues/476.
Also this change improves performance of reduce algorithm as `reduce_on_gpu` is not efficient on CPU. 
```
Device: AMD Phenom(tm) II X3 710 Processor (CPU)
=== accumulate with compute === [ MASTER, reduce_on_gpu is used]
size,time (ms)
2,0.179798
4,0.186708
8,0.172284
16,0.187684
32,0.163798
64,0.185535
128,0.173303
256,0.186923
512,0.168256
1024,0.173956
2048,0.200156
4096,0.235499
8192,0.282913
16384,0.664291
32768,0.699428
65536,1.259930
131072,2.511260
262144,4.673290
524288,9.389420
1048576,17.946400
2097152,38.079900
4194304,76.685300 …
```
> Using serial_reduce() when reducing on CPU device

- include/boost/compute/algorithm/detail/find_if_with_atomics.hpp
This addresses https://github.com/boostorg/compute/issues/27.
I added `find_if_with_atomics_multiple_vpt()` which checks multiple values per thread. I kept original algorithm (it's renamed to `find_if_with_atomics_one_vpt()`) as I had found out that it's better for small and medium-sized inputs (depends on GPU; by default it's used for buffers with elements or less 1048576, but it's "tunable"). Probably it happens so because its kernel is much simpler. 
`find_if_with_atomics_multiple_vpt()` has two kernels - one for GPUs, one for CPUs or most generally for devices which have relativity big cache per compute unit. In the first reads from global memory are coalesced, in the second one reads from global memory are order so the big cache is efficiently used.
For GPUs default values per thread …
> Checking multiple values per thread in find_if()

- include/boost/compute/algorithm/detail/find_extrema.hpp
- include/boost/compute/algorithm/detail/find_extrema_reduce.hpp
- include/boost/compute/algorithm/detail/find_extrema_with_atomics.hpp
- include/boost/compute/algorithm/detail/find_extrema_with_reduce.hpp
- include/boost/compute/algorithm/detail/serial_find_extrema.hpp
- include/boost/compute/algorithm/max_element.hpp
- include/boost/compute/algorithm/min_element.hpp
- include/boost/compute/algorithm/minmax_element.hpp
- perf/perf_bolt_max_element.cpp
- perf/perf_max_element.cpp
- test/test_extrema.cpp
This resolves https://github.com/boostorg/compute/issues/460.
[1] I fixed perf_max_element benchmark. It needed a fix because `max_element` was called in this way:
```cpp
max = *boost::compute::max_element(device_vector.begin(), device_vector.end(), queue);
```
It includes reading found maximum from device memory using `*` dereference operator (it's very inefficient way to read data as it includes creating command queue which takes almost 2 ms). Now execution time does not contain time of reading maximum value from memory.
[2] I added support for custom comparison function in `find_extrema()` (therefore for `max_element()`, `min_element()` and `minmax_element()` functions).
[3] I renamed `find_extema_reduce()` to `find_extrema_with_reduce()` so it matches naming convention.
Benchmark …
> Support for custom comparison function in find_extrema()

- include/boost/compute/system.hpp
- test/test_command_queue.cpp
See https://github.com/boostorg/compute/issues/505
> fix a few instances where the device type is not used as a bit mask

- include/boost/compute/algorithm.hpp
I forgot to add reduce by key in algorithm.hpp meta-header, this is a fix for that.
> Include Reduce by key in algorithm.hpp meta-header

- include/boost/compute/algorithm/search.hpp
- include/boost/compute/algorithm/search_n.hpp
- test/test_search.cpp
- test/test_search_n.cpp
This addresses https://github.com/boostorg/compute/issues/245.
I found the bug:
If you analyse [search_n](https://github.com/boostorg/compute/blob/master/include/boost/compute/algorithm/search_n.hpp) (check lines 52, 53, 79), you'll see that it puts 1 or 0 in the first `iterator_range_size(t_first, t_last) + 1 - n` positions (that happens in kernel), but later first occurrence of value 1 is searched in range `[matching_indices.begin(); matching_indices.end())` (line 121). The same bug is in `search`.
I fixed it by reducing the size of `matching_indices` to `iterator_range_size(t_first, t_last) + 1 - n`  and adding if clause for cases when pattern does not occur in input vector.
I also added tests to make sure that the pattern gets found even when it occurs at the end of the input vector.
> Fix for search and search_n algorithm

- include/boost/compute/algorithm/detail/binary_find.hpp
- perf/perf_binary_find.cpp
- test/test_binary_search.cpp
This fixes binary_find algorithm. There was a bug which resulted in iterators going out of range and causing errors. Thanks to StreamComputing for reporting this.
Unfortunately, binary_search test could not find those errors as the test data was too small and binary_find kernel was not used (while loop condition was false from the beginning). I fixed that in the first commit. You can check that tests fails on this commit (binary_find is fixed in the next one).
I also improved performance of binary_find. The kernel was compiled in every while loop iteration, now it's compiled only once.
```
=== binary_find with compute === [ MASTER ]
size,time (ms)
2,0.151978
4,0.224376
8,0.224038
16,0.223790
32,0.224597
64,0.233016
128,0.225822
256,0.333630
512,0.320126
1024,0.314016
2048,0.336053 …
```
> Fix and improve binary_find

- include/boost/compute/types/struct.hpp
- test/test_struct.cpp
This adds support for C-style arrays (e.g. "int array[10]") to the
BOOST_COMPUTE_ADAPT_STRUCT() macro.
Thanks to Fabian Bösch for providing the code.
> Add array support to BOOST_COMPUTE_ADAPT_STRUCT()

- include/boost/compute/command_queue.hpp
- test/test_image2d.cpp
This addresses https://github.com/boostorg/compute/issues/365 (https://github.com/boostorg/compute/pull/496 only partiality fixed that issue). Now `enqueue_map_buffer()` returns associated event through non-const parameter `map_buffer_event` (there is also overload without this parameter).
I also added missing enqueue_map_image method (with test in `test_image2d.cpp`) and asynchronous versions for enqueue_map_buffer(), enqueue_read_buffer_rect() and enqueue_write_buffer_rect().
> Events for queue enqueue_map_ methods

- perf/perf_bolt_saxpy.cpp
- test/test_buffer.cpp
- test/test_command_queue.cpp
- test/test_copy.cpp
- test/test_fill.cpp
- test/test_image1d.cpp
- test/test_image2d.cpp
- test/test_pipe.cpp
- test/test_svm_ptr.cpp
- test/test_user_event.cpp
I installed AMD APP SKD 3.0 which has OpenCL 2.0 `cl.h` (`CL_VERSION_2_0` macro is defined in it) and since my GPU does not support OpenCL 2.0 I got errors with some tests. 
I fixed it by adding runtime OpenCL version check in those tests. I did the same with tests that require OpenCL 1.1 or 1.2. Now you can have `cl.h` defining `CL_VERSION_2_0` and OpenCL 1.0 device and tests should pass.
> Runtime OpenCL version check in tests

- test/test_fill.cpp
This skips the tests for fill() and fill_n() with double values
if the device does not support the cl_khr_fp64 extension.
> Skip fill() tests with double if not supported by device

- include/boost/compute/container/vector.hpp
- test/test_vector.cpp
See https://github.com/boostorg/compute/issues/523. 
In the first commit I added test for vector's move constructor when custom allocator is used (in that case `boost::computer::pinned_allocator<T>`).  You can checkout to this commit and see that test fails on `BOOST_CHECK(a.size() == 0)` and `BOOST_CHECK(a.get_buffer().get() == 0)` as the copy constructor is used instead of the move ctor.  It also crashes because of some memory access violation that I can not locate right now.
Second commit adds more tests for vector when used with custom allocator.
The last commit includes fixes @pisto presented in https://github.com/boostorg/compute/issues/523 + I added `queue` parameter to copy constructor and a copy constructor for situations when different allocators are used.
> Vector with custom allocator fix

- include/boost/compute/algorithm/detail/find_extrema_with_atomics.hpp
- include/boost/compute/algorithm/detail/find_extrema_with_reduce.hpp
- perf/perf_max_element.cpp
- test/test_extrema.cpp
This fixes the bug with `find_extrema_with_atomics` and `find_extrema_with_reduce` not always returning iterator to the first extremum (`serial_find_extrema` works correctly).
In the first commit I've modified tests to show this problem. You can checkout to it and see that tests will fail. In the second and the third algorithms are modified to take value index in input data into account if compared values are equal.  
Additionally, in order to increase the performance of `find_extrema_with_reduce` I used zero-copy (pinned) memory. 
Performance tests (on GPU AMD Radeon HD7770 1GB) for  `find_extrema_with_reduce`:
```
less<input_type>:
=== max_element with compute === [MASTER]
size,time (ms)
< serial version is used for smaller inputs 
512,0.221056
1024,0.212490
2048,0.195597
4096,0.207009 …
```
> Fix find_extrema_with_atomics and _with_reduce

- test/quirks.hpp
- test/test_copy.cpp
- test/test_fill.cpp
- test/test_svm_ptr.cpp
See #528.
I replaced broken `enqueue_svm_memcpy()` operations with map, copying and unmap in `test_fill.cpp` and `test_svm_ptr.cpp`.
I also added required `-cl-std=CL2.0` build option in `sum_svm_kernel` test case ([clBuildProgram](https://www.khronos.org/registry/cl/sdk/2.0/docs/man/xhtml/clBuildProgram.html): *Applications are required to specify the –cl-std=CL2.0 option if they want to compile or build their programs with OpenCL C 2.0.*").
This branch is based on develop, because otherwise there are conflicts.
> Fix OpenCL 2.0 test cases in test_fill and test_svm_ptr

- include/boost/compute/program.hpp
- test/test_program.cpp
Calling boost::compute::program::create_with_source_file silently creates a program if the input filename is incorrect.  Even program.build() succeeds.  This patch throws std::ios_base::failure if stream.fail() is true.  This seems preferable to something else failing way downstream because of a typo in the filename.
I added a test, but didn't actually test it since I'm using this outside the standard boost build system.  I think it should work, but it's easy to figure out what it does.  It simply tries to create a program from a source file, where the filename is an empty string.  The test verifies that this throws.
> program::create_with_source_file doesn't fail with bad input

- include/boost/compute/algorithm/detail/binary_find.hpp
- include/boost/compute/algorithm/max_element.hpp
- include/boost/compute/algorithm/min_element.hpp
- include/boost/compute/algorithm/minmax_element.hpp
See http://boost.cowic.de/rc/docs-inspect-develop.html#compute
It fixes:
```
boost/compute/algorithm/detail/binary_find.hpp: *M* violation of Boost min/max guidelines on line 117, *M* violation of Boost min/max guidelines on line 118, *M* violation of Boost min/max guidelines on line 120, *M* violation of Boost min/max guidelines on line 121
boost/compute/algorithm/max_element.hpp:
(line 27) Non-ASCII: /// \param compare comparison function object which returns ​true if the firs
boost/compute/algorithm/min_element.hpp:
(line 27) Non-ASCII: /// \param compare comparison function object which returns ​true if the firs
boost/compute/algorithm/minmax_element.hpp:
(line 30) Non-ASCII: /// \param compare comparison function object which returns ​true if the firs
```
If I remember correctly …
> Minor fixes related to Boost Inspection Report (1.60 develop)

- include/boost/compute/random/linear_congruential_engine.hpp
- include/boost/compute/random/mersenne_twister_engine.hpp
- include/boost/compute/random/threefry_engine.hpp
In `generate` methods in `mersenne_twister_engine`, `linear_congruential_engine` and `threefry_engine` classes there are incorrect updates of count variables. They leads to assigning out-of-range in used kernels. (`#include <algorithm> ` is added for `std::min`.)
In `linear_congruential_engine` there is incorrect `seed` method call: there is no `seed` method with just one parameter of type result_type.
> Fix incorrect count update in rngs

- include/boost/compute/random/mersenne_twister_engine.hpp
- test/test_mersenne_twister_engine.cpp
The copy ctor and assign op of compute::mersenne_twister_engine does not copy its states. So copied engine causes "Invalid Program" error.
This modification solves this problem.
> Modify mersenne_twister_engine to copy its states.

- include/boost/compute/random/linear_congruential_engine.hpp
- test/test_linear_congruential_engine.cpp
The copy ctor and the assign op of compute::linear_congruential_engine does not copy its all states. So copied engine causes "Invalid Program" error.
This modification solves this problem.
> Modify linear_congruential_engine to copy its all states.

- test/test_copy.cpp
- test/test_svm_ptr.cpp
see [compute - test_svm_ptr](http://www.boost.org/development/tests/develop/developer/output/Flast-FreeBSD10-gcc-5-2-0~gnu++11-boost-bin-v2-libs-compute-test-test_svm_ptr-test-gcc-5-2-0-debug.html) and [compute - test_copy](http://www.boost.org/development/tests/develop/developer/output/Flast-FreeBSD10-gcc-5-2-0~gnu++11-boost-bin-v2-libs-compute-test-test_copy-test-gcc-5-2-0-debug.html)
> Fix missing includes.

- include/boost/compute/algorithm/detail/find_extrema_with_reduce.hpp
- include/boost/compute/algorithm/detail/reduce_by_key_with_scan.hpp
- include/boost/compute/types/fundamental.hpp
- test/test_extents.cpp
- test/test_image1d.cpp
- test/test_image2d.cpp
- test/test_kernel.cpp
- test/test_scatter_if.cpp
- test/test_vector.cpp
- test/test_wait_list.cpp
These are the changes I think should fix some of the problems encountered [here](http://www.boost.org/development/tests/develop/developer/compute.html) on Timber OSX.
The first and the third commits are obvious.  They fix: [warning: comparison between signed and unsigned integer expressions](http://www.boost.org/development/tests/develop/output/timber-osx-compute-darwin-5-3-0-warnings.html#test_image2d) (there is one exception, I can't locate the bug in `test_fill`) and [test_scatter_if fail](http://www.boost.org/development/tests/develop/developer/output/timber-osx-boost-bin-v2-libs-compute-test-test_scatter_if-test-darwin-5-3-0-debug.html).
The second and the forth commits should fix [test_extrema fail](http://www.boost.org/development/tests/develop/developer/output/timber-osx-boost-bin- …
> Timber OSX fixes

- .travis.yml
- perf/perf_fill.cpp
- disable running tests in linux build as fglrx does not work,
- use OpenCL-ICD to in linux build (now we can at least build tests), 
- enable OSX build 
- currently it's allowed to fail as there are many ``Invalid Work Group Size`` errors, some are legit, some are very weird
- only clang as building with gcc gives ``Undefined symbols for architecture x86_64:`` errors I don't know how to fix (see https://travis-ci.org/boostorg/compute/jobs/107840912#L3677)
I'll later try POCL drivers + linux. I don't know if we can use Intel OpenCL driver as it works only on Intel CPU (Core, Xeon etc.) and I'm not sure if builds always run on machine with Xeon CPU.
> Update Travis CI config

- include/boost/compute/container/valarray.hpp
- perf/perf_stl_sort.cpp
- perf/perf_thrust_accumulate.cu
- perf/perf_thrust_exclusive_scan.cu
- perf/perf_thrust_partial_sum.cu
- perf/perf_thrust_partition.cu
- perf/perf_thrust_reduce_by_key.cu
- perf/perf_thrust_reverse.cu
- perf/perf_thrust_reverse_copy.cu
- perf/perf_thrust_rotate.cu
- perf/perf_thrust_sort.cu
- perf/perf_thrust_unique.cu
- test/quirks.hpp
- test/test_buffer.cpp
This PR fixes:
* missing <iostream> includes in some benchmarks
* valarray binary operators (they didn't work on POCL)
* buffer test, now destructor callback test is not run for POCL devices (POCL does not support clSetMemObjectDestructorCallback)
After those commits Boost.Compute works with POCL + OpenCL 1.1 headers (all tests pass for me).
> Misc fixes

- .travis.yml
- .travis/amd_sdk.sh
- test/quirks.hpp
- test/test_program.cpp
This PR adds POCL builds and updates Khronos ICD builds (new ICD, builds moved to Travis CI container-based infrastructure).
* I wasn't able to build POCL on Precise (container-based infrastructure) due to `lrt` (real time clock library) related error, so POCL is on Trusty.
* I used direct linkage and because POCL lacks some OpenCL 1.2 runtime functions OpenCL 1.0 and 1.1 headers are used in POCL builds .  
* clang 3.7 is used in POCL builds , but not in Boost.Compute build due to this https://svn.boost.org/trac/boost/ticket/11664 error.
* OpenCL 1.2 and 2.0 headers are used in Khronos ICD builds.
After this PR there'll be 8 Linux builds and 1 OSX build:
* 14.04 (Trusty), POCL, clang 3.5/gcc 4.8, OpenCL 1.0/1.1, build + tests
* 12.04 (Precise, container-based infrastructure), Khronos ICD, …
> [Travis CI] Add POCL builds 

- doc/Jamfile.v2
Thie fixes the stylesheet and navigation images at http://www.boost.org/doc/libs/master/libs/compute/doc/html/index.html
> Configure documentation to use boost paths.

- doc/faq.qbk
Mention that VexCL is in fact may use Boost.Compute as a backend.
> Fix FAQ section regarding differences with existing libraries

- .travis.yml
- example/opencl_test.cpp
- include/boost/compute/command_queue.hpp
- include/boost/compute/detail/diagnostic.hpp
- test/Jamfile.v2
- test/test_command_queue.cpp
This is a fast fix for https://github.com/boostorg/compute/issues/563 (+ I've suppressed some other warning for MSVC that are just annoying) . 
I'll later remove lines
```
<toolset>gcc:<cxxflags>-Wno-deprecated-declarations # Deprecated declarations in CL/cl.h
<toolset>clang:<cxxflags>-Wno-deprecated-declarations # Deprecated declarations in CL/cl.h
<toolset>darwin:<cxxflags>-Wno-deprecated-declarations # Deprecated declarations in CL/cl.h
<toolset>msvc:<cxxflags>/wd4996 # Deprecated declarations in CL/cl.h
```
and suppress deprecated declarations warning (related to CL/cl.h) in the code.
> Update tests compile options in Jamfile.v2

- .travis.yml
- include/boost/compute/algorithm/detail/merge_with_merge_path.hpp
- include/boost/compute/algorithm/includes.hpp
- include/boost/compute/iterator/strided_iterator.hpp
- test/test_strided_iterator.cpp
Unfortunately, commit 3826e9cae47f56d6ce91a6127800bce979155a0c (fixing some unsigned/signed int comparison warnings on Windows) introduced compilation errors for OSX that I did not notice. 
See build 1300.9: https://travis-ci.org/boostorg/compute/builds/115231140.
This PR fixes those erros and add OSX Travis-CI build without running tests (because currently a few tests fail on OSX) in order to avoid such a mistakes in the future. (OSX build with tests is still allowed to fail.) There is also a small code refactoring in `strided_iterator.hpp`  .
> Fix compilation errors on OSX

- .travis.yml
- include/boost/compute/detail/parameter_cache.hpp
- perf/perf.hpp
- perf/perf_saxpy.cpp
- test/test_buffer.cpp
* Now 0.13 version of POCL is used instead of `master`-branch version.
* Fix for AMD APP SDK v3.0 builds, AMD updated the SDK and nothing works as it did :) I opened an [issue ](https://community.amd.com/thread/198900) on AMD forum, maybe they'll fix it later.
* Minor fixes in `test_buffer`, `parameter_cache` and `perf_saxpy`
> Build fixes and other

- include/boost/compute/utility/wait_list.hpp
- test/test_wait_list.cpp
Constructing a wait_list from an initializer list is often convenient.
> Add initializer list constructor to wait_list

- example/opencv_optical_flow.cpp
Image sampler should be a global constant in OpenCL program. See [this](https://groups.google.com/forum/#!topic/boost-compute/RWvaCsEIcL4).
> Fix bug in optical flow example

- include/boost/compute/algorithm/detail/radix_sort.hpp
- include/boost/compute/algorithm/sort.hpp
- include/boost/compute/algorithm/sort_by_key.hpp
- include/boost/compute/algorithm/stable_sort.hpp
- test/test_radix_sort.cpp
- test/test_radix_sort_by_key.cpp
This should fix https://github.com/boostorg/compute/issues/588.
Now in radix sort when `greater<T>()` is specified as comparison function (desc order) instead of performing asc-ordered radix sort and then reversing the result, descending radix sort is performed.
It's done by negating input value if its type is a signed type and by subtracting the input value from the maximum value of value's type in other cases (in `radix()` function). That way values seem "reversed" and we get desc order. It should also be faster than sorting in asc order and then reversing the result.
I also added some test for desc-ordered radix sort and radix sort by key.
> Fix radix_sort_by_key for desc order

- include/boost/compute/detail/literal.hpp
- test/CMakeLists.txt
- test/test_literal_conversion.cpp
boost::compute::detail::make_literal is losing some precision when making literal floating point values because it uses std::numeric_limits<T>::digits10, but that only gives us the number of decimal digits that will survive a decimal->native>decimal conversion; what we are doing is a native->decimal->native conversion, which can require up to ::max_digits10 (which is larger than ::digits10 by 2 (double) or 3 (float)).
However, max_digits10 is a c++11 feature, so this commit uses digits10 + 3 when the c++11 numeric_limits isn't available.  That should be enough for an IEEE-style float, though is slightly more than necessary for some (e.g. double).
I also added a test for this (which fails with the current conversion for both float and double, and passes with the proposed commits).
> Increase make_literal precision

- include/boost/compute/random/uniform_real_distribution.hpp
- test/test_uniform_real_distribution.cpp
Related to https://github.com/boostorg/compute/issues/587. 
Now generated floating-point values are uniformly distributed on the interval `[a, b)` and no value is greater or equal to `b`.
I also added test that checks if results are in fact in `[a,b)` range (by using `range_test_engine` class that generates max random value or zeroes).
> Fix uniform real distribution 

- include/boost/compute/algorithm/detail/search_all.hpp
- include/boost/compute/algorithm/find_end.hpp
- test/test_find_end.cpp
I've found out what's wrong in the `find_end` algorithm. Using uninitialized memory (from the end of `matching_indices`) was causing undefined behaviour. It was uninitialized because `search_kernel` does not initialize the last `<pattern_size> - 1` elements of `matching_indices` as the pattern can not start there. Now it's fixed.
> Fix find_end algorithm

- test/test_literal_conversion.cpp
The tests are failing under OS X/clang, but it isn't obvious to me why, or exactly which part is failing.  This commit simplifies the test code by ignoring the stringstream I/O status, and reorganizes it to be clearer whether it's the initial conversion to string that is failing, or the subsequent conversion back from string.
(This may or may not clear up the OSX/clang failure, but it's better test code anyway).
This also incorporates the PR #603 fix.
> Literal test simplification

- include/boost/compute/algorithm/copy.hpp
- test/test_copy.cpp
This enables copying data using `clEnqueueCopyBuffer()` in `boost::compute::copy()` algorithm when user passes `device_ptr<>`/s.
> Enable copying with copy buffer op for device_ptr

- .travis.yml
This PR introduces minor changes to Travis-CI build script.
1. Now there is one dedicated build for Coveralls (Trusty, g++ 4.8, AMD APP SDK v2.9.1, OpenCL 1.2). It should make POCL builds slightly faster. Unfortunately, it's not possible to use g++ 4.8 on Precise (Travis CI container-based infrastructure) and get coverage from it (only g++ builds give coverage info).
2. Now we do not push coverage info of tests to the Coveralls.
> Dedicated build for coveralls

- include/boost/compute/random/discrete_distribution.hpp
- test/test_discrete_distribution.cpp
Resolves https://github.com/boostorg/compute/issues/612. I've also added `min()` and `max()` methods and changed `boost::compute::discrete_distribution` so now it generates `IntType` values instead of always generating `uint` values.
> Default constructor for discrete distribution

- .travis.yml
Two additional Travis-CI builds (gcc and clang) to be sure that Boost.Compute works with libraries from the latest Boost version. Spoiler: it works.
POCL builds may not work now. It has nothing to do with this pull-request, it's just because llvm [turned off their APT mirror](http://lists.llvm.org/pipermail/llvm-foundation/2016-May/000020.html) and gpg key can't be download.
> Add Travis CI build with latest Boost libs

- .travis.yml
Apt for llvm and clang has been down for quite some time (see https://github.com/travis-ci/travis-ci/issues/6120), so here is the fix for POCL builds which require the latest clang and llvm.
> Temp. fix for llvm apt being down

- include/boost/compute/algorithm/adjacent_difference.hpp
- include/boost/compute/algorithm/detail/merge_sort_on_gpu.hpp
- include/boost/compute/algorithm/detail/reduce_on_cpu.hpp
- include/boost/compute/algorithm/reduce.hpp
- test/test_adjacent_difference.cpp
```
Device: Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (4/4 cores/threads)
=== accumulate with stl ===
size,time (ms)
2,0.000133
4,0.000133
8,0.000133
16,0.000135
32,0.000136
64,0.000139
128,0.000151
256,0.000165
512,0.000189
1024,0.000238
2048,0.000463
4096,0.000758
8192,0.001401
16384,0.002684
32768,0.005183
65536,0.009545
131072,0.018869
262144,0.033239
524288,0.059656
1048576,0.119746
2097152,0.295889
4194304,0.606165
8388608,1.219240
16777216,2.450350
33554432,4.898130
[master]
=== accumulate with compute ===
size,time (ms)
2,0.022182
4,0.021758
8,0.021698
16,0.021807
32,0.024980
64,0.021770
128,0.025144
256,0.025538
512,0.025886
1024,0.026272
2048,0.026631
4096,0.024762
8192,0.030600
16384,0.034140
32768,0.043930
65536,0.063510
131072,0.102598
262144,0.181727
524288,0.377996 …
```
> Reduce for CPU

- include/boost/compute/algorithm/detail/copy_on_device.hpp
- include/boost/compute/detail/vendor.hpp
This improves `transform()` (`copy_on_device()`) performance for multicore CPUs.
```
=== saxpy with stl ===
size,time (ms)
2,0.000160
4,0.000173
8,0.000200
16,0.000214
32,0.000225
64,0.000260
128,0.000944
256,0.001346
512,0.002352
1024,0.004416
2048,0.008575
4096,0.012101
8192,0.023922
16384,0.048170
524288,0.962686
1048576,1.929100
2097152,3.858070
4194304,7.719810
8388608,15.428000
16777216,30.873400
33554432,61.704100
[master]
=== saxpy with compute (CPU, Intel i5-6600K, 4/4 cores/threads) ===
size,time (ms)
2,0.024186
4,0.024106
8,0.024319
16,0.023895
32,0.024225
64,0.024235
128,0.024309
256,0.027449
512,0.027538
1024,0.028694
2048,0.029796
4096,0.031381
8192,0.028765
16384,0.039954
32768,0.045763
65536,0.063319
131072,0.087354
262144,0.130503
524288,0.292780
1048576,0.643207 …
```
> Transform for multicore CPUs

- include/boost/compute/container/array.hpp
- include/boost/compute/container/vector.hpp
- test/test_array.cpp
- test/test_for_each.cpp
- test/test_malloc.cpp
- test/test_reduce.cpp
- test/test_rotate.cpp
- test/test_scan.cpp
- test/test_scatter.cpp
- test/test_scatter_if.cpp
- test/test_sort.cpp
- test/test_string.cpp
- test/test_vector.cpp
This fixes 3 things:
* `boost::compute::array<T>` was not working correctly with context different than `system::default_context()` since it was using `default_queue()` in its methods (so wild `Invalid context` errors could appear).
* I added
```cpp
template<class OtherAlloc>
vector& operator=(const vector<T, OtherAlloc> &other)
{
}
```
for `boost::compute::vector<T, A>, so now something like this:
```cpp
vector<int, some_allocator> b(context);
vector<int, different_allocator> a(context);
vector<int, some_allocator> c = a; // this works in `develop`
a = b; // this does not work in `develop`, works now
```
works.
* I changed several tests so in the future we can change `Context::context, Context::queue, Context::device` and tests will run using those context, queue and device, not the …
> Various fixes

- include/boost/compute/algorithm/detail/find_extrema.hpp
- include/boost/compute/algorithm/detail/find_extrema_on_cpu.hpp
- include/boost/compute/algorithm/detail/find_extrema_with_reduce.hpp
- include/boost/compute/algorithm/detail/reduce_on_cpu.hpp
- test/test_extrema.cpp
* Add find_extrema() for multicore CPUs.
```
=== max_element with stl ===
size,time (ms)
2,0.000132
4,0.000133
8,0.000135
16,0.000138
32,0.000148
64,0.000161
128,0.000193
256,0.000258
512,0.000388
1024,0.000653
2048,0.001178
4096,0.002227
8192,0.004331
16384,0.008531
32768,0.016933
65536,0.033753
131072,0.067367
262144,0.134580
524288,0.269013
1048576,0.537921
2097152,1.088980
4194304,2.183200
8388608,4.367510
16777216,8.733790
33554432,17.461000
[master]
=== max_element with compute ===
size,time (ms)
2,0.027686
4,0.026849
8,0.026995
16,0.026756
32,0.027935
64,0.026681
128,0.027340
256,0.027736
512,0.027438
1024,0.027745
2048,0.028904
4096,0.031220
8192,0.034191
16384,0.038634
32768,0.049738
65536,0.069393
131072,0.111162
262144,0.165911
524288,0.364886
1048576,0.699782
2097152,1.385050 …
```
> find_extrema for CPUs

- include/boost/compute/algorithm/detail/scan.hpp
- include/boost/compute/algorithm/detail/scan_on_cpu.hpp
- include/boost/compute/algorithm/detail/scan_on_gpu.hpp
- include/boost/compute/algorithm/detail/serial_scan.hpp
- perf/perf_partial_sum.cpp
- perf/perf_stl_partial_sum.cpp
- test/test_scan.cpp
This adds parallel scan for multicore CPUs. 
Unfortunately, it's not so much faster compared to `serial_scan` as you may think (at least in the simplest version of scan). Turns out that scan (partial_sum) is very memory bound operation and that's what limits the performance. If your scan is more computational intensive, like using multiplication as binary operator (instead of addition) or using `transform_iterator`, new implementation is much faster.
There is a parameter, a knob for `serial_scan`, so if anyone prefers that it's easy to force it. 
1st test:
* Integers (4 bytes)
* Output is a different buffer than input
* Addition as binary operator
```
=== partial_sum with stl ===
size,time (ms)
2,0.000133
4,0.000142
8,0.000134
16,0.000138
32,0.000143
64,0.000160
128,0.000182
256,0.000231 …
```
> Scan for multicore CPUs

- include/boost/compute/algorithm/transform_if.hpp
I think it is faster this way, avoiding separate reduction.
> transform_if_impl optimization: avoid reduction

- include/boost/compute/command_queue.hpp
At least on NVIDIA most of the OpenCL commands like clEnqueueNDRangeKernel won't return an error if it happened inside kernel. Instead failure will be reported when command queue is flushed. So it is convenient to check errors in kernel by adding clFinish call after enqueue.
> check result of flush and finish

- include/boost/compute/command_queue.hpp
I wanted to play with device-side enqueue in OpenCL 2.x but it was not available in Boost.Compute.
Here are the missing properties.
On the longer term, do we want device command queue objects like the DeviceCommandQueue in https://github.com/KhronosGroup/OpenCL-CLHPP/blob/master/input_cl2.hpp#L8143 ?
> Add OpenCL 2.0 command queue properties

- .travis.yml
- include/boost/compute/iterator/buffer_iterator.hpp
- include/boost/compute/iterator/counting_iterator.hpp
- include/boost/compute/iterator/function_input_iterator.hpp
- include/boost/compute/iterator/permutation_iterator.hpp
- include/boost/compute/iterator/strided_iterator.hpp
- include/boost/compute/iterator/transform_iterator.hpp
- include/boost/compute/iterator/zip_iterator.hpp
This addresses https://github.com/boostorg/compute/issues/665. I also made all index expression immutable.
> Fix buffer_iterator_index_expr

- include/boost/compute/detail/duration.hpp
This adds a "BOOST_COMPUTE_NO_BOOST_CHRONO" which disables
including/using Boost.Chrono from Boost.Compute.
> Add BOOST_COMPUTE_NO_BOOST_CHRONO configuration macro

- test/Jamfile.v2
- test/check/has_opencl.cpp
This change avoids massive of test failure that's caused by no opencl env.
> Check opencl availability on test.

- include/boost/compute/detail/parameter_cache.hpp
- test/test_lambda.cpp
Fixes https://github.com/boostorg/compute/issues/673.
> Various fixes for Visual Studio 

- include/boost/compute/program.hpp
In build_with_source(), when BOOST_COMPUTE_USE_OFFLINE_CACHE is set, we use boost::uuids::detail::sha1 to compute the SHA1 of the program source, options, etc, and use it as the unique key to manage cached objects.
When the hash is converted to a string and passed to load_program_binary() and save_program_binary(), the conversion function of object detail::sha1 is called, which then calls  boost::uuids::detail::sha1::get_digest(). If you take a look at http://www.boost.org/doc/libs/1_63_0/boost/uuid/sha1.hpp, the sha1::get_digest() function actually appends some bytes to the string each time called. Thus, each time when we call get_digest() we get a different SHA1. 
Thus, the hash string used as the parameter to load_program_binary() and save_program_binary() are always different, because …
> fix SHA1 hash in build_with_source()

- include/boost/compute/interop/opengl/context.hpp
Check that a platform supports OpenCL/OpenGL sharing before attempting to load the clGetGLContextInfoKHR() extension function in function opengl_create_shared_context().
> Check platform extension for issue #676

- test/quirks.hpp
`clEnqueueSVMMemcpy()` works for AMD devices on Windows (Linux Catalyst drivers still without an update).
> AMD SVM bug was fixed on Windows

- test/Jamfile.v2
The use of 'compile' rule interferes with --dump-tests option of b2 and prevents correct running of tests in some of the other Boost libraries.
See discussion: http://boost.2283326.n4.nabble.com/build-geometry-regression-Geometry-develop-regression-tests-are-blank-td4693186.html
> Use 'obj' rule instead of 'compile' in opencl availability test.

- include/boost/compute/algorithm/detail/radix_sort.hpp
- include/boost/compute/type_traits/type_definition.hpp
- test/test_sort_by_key.cpp
Based on https://github.com/boostorg/compute/pull/568 I prepared a fix for radix sort by key algorithm. Fixes #162.
In https://github.com/haahh/compute/commit/f1160bbc1f513224709b26a19875589260e63560 I did the same fix but using different approach. If you think it's better I'll make pull request with that one.
> radix sort by key with custom value type, fixes #162

- test/test_command_queue.cpp
- test/test_extents.cpp
- test/test_vector.cpp
Some tests should not be run if macro `BOOST_COMPUTE_NO_HDR_INITIALIZER_LIST` is defined.
> Fix for #484

- include/boost/compute/detail/path.hpp
- include/boost/compute/interop/opengl/context.hpp
In two places of Boost.Compute, the macro WIN32 is used to detect Windows environment.
However, this macro is undefined on g++ when C++11 or C++0x is used. This can cause a crash in detail/path.hpp, because the incorrect path will be used.
There are some discussions on the Internet regarding this issue:
https://github.com/RcppCore/Rcpp/issues/360
https://sourceforge.net/p/mingw-w64/discussion/723798/thread/4ce97145/
I tried to compile the following code in MinGW, with GCC 6.3.0
```
#ifndef WIN32
#error Define WIN32 is missing!
#endif
#ifndef _WIN32
#error Define _WIN32 is missing!
#endif
int
main()
{
return 0;
}
```
And when c++11 or c++0x is used, WIN32 will not be defined:
```
D:\github_repos>g++ -o test test.cpp
D:\github_repos>g++ -std=c++11 -o test test.cpp
test.cpp:2:10: error: …
```
> use _WIN32 instead of WIN32

- include/boost/compute/container/valarray.hpp
This fixes `valarray(const valarray<T> &other)` copy ctor.
> Fix valarray copy ctor

- doc/Jamfile.v2
- include/boost/compute/command_queue.hpp
- include/boost/compute/device.hpp
- include/boost/compute/kernel.hpp
- include/boost/compute/program.hpp
- test/test_command_queue.cpp
Adds `set_as_default_device_queue()` (wrapper for `clSetDefaultDeviceCommandQueue`) and ` get_default_device_queue()` methods to `command_queue` class.
> Default device queue

- include/boost/compute/algorithm/copy.hpp
- include/boost/compute/container/vector.hpp
- test/test_vector.cpp
This pull-request:
* fixes warning referenced in #730,
* implements `boost::compute::vector::shrink_to_fit()` (which resolves #732), and
* fixes memory management issue in `boost::compute::vector`: memory deallocation should depend on `vector`'s capacity, not on its `m_size`.
> Implement vector::shrink_to_fit()

- include/boost/compute/types.hpp
- include/boost/compute/types/size_t.hpp
The types do not resolve to `ulong` and `long` on OSX, as opposed to other platforms.
See ddemidov/vexcl#222
> size_t and ptrdiff_t need special treatment on OSX

- .travis.yml
- .travis/amd_sdk.sh
- include/boost/compute/iterator/strided_iterator.hpp
- test/test_strided_iterator.cpp
Using `std::iterator_traits<>` to get `iterator_catagory` prevents from converting STL iterator tag to Boost tag.
Fixes #741
> Fix strided_iterator tag

- include/boost/compute/exception/program_build_failure.hpp
- include/boost/compute/program.hpp
- test/data/invalid_program.cl
- test/quirks.hpp
- test/test_program.cpp
Good day!
I've prepared changes to change an exception type thrown by program::build() when program build fails (discussion can be found [here](https://github.com/boostorg/compute/issues/750))
There's one question left - whom should I mention in copyright notices in new files?
Thanks for your time,
Kristian Popov
> program::build() method throws a failure exception that contains a build log

- include/boost/compute/detail/sha1.hpp
This suppresses the warning at
https://github.com/boostorg/uuid/blob/boost-1.66.0/include/boost/uuid/sha1.hpp#L13
> boost/uuid/sha1.hpp is deprecated since v1.66

- include/boost/compute/algorithm/random_shuffle.hpp
`std::random_shuffle` was deprecated in C++14 and deleted in C++17.  `std::shuffle` was added in C++11.  using it fixes build issues with clang+libc++ when compiling with `-std=c++1z`.
fixes issue #760
This is my first attempt at contributing.
I do not consider this trivial change to be worthy of copyright, but I work for Intel and will get the open-source contribution paperwork approved ASAP.
> use std::shuffle for post-C++11

- include/boost/compute/interop/opengl/context.hpp
It looks as though the author's intention was to use different extension name for different platforms. 
For some reason, however, commit 114e444a7ea88055460f8dd76c6cc76032df6b18 introduced a change that ignores the platform-specific `cl_gl_sharing_extension` variable and uses a string instead, whose value doesn't seem right (and it doesn't work on my system).
> Use system-dependent CL<->GL sharing extension name instead of hardcoded string

- .appveyor.yml
Use `CL_TARGET_OPENCL_VERSION` to set a maximum version instead (not added to this PR unless AppVeyor fails). See https://github.com/KhronosGroup/OpenCL-Headers. The `master` branch is now the only branch.
> Fix Appveyor requesting missing OpenCL branch

- include/boost/compute/algorithm/detail/merge_sort_on_gpu.hpp
- test/test_sort.cpp
I have modified test case to reproduce the issue as described in #774. And a fix is proposed
Tested on:
* Nvidia Geforce GTX1060 
* AMD Radeon HD 6770
> Fix duplicates using custom compare with bitonic block sort

- example/simple_moving_average.cpp
Variable shadowing is occurred with bool and float 'ret', as result check_results function always return true
> fix variable shadowing in check_results(simple moving average example)

- include/boost/compute/algorithm/detail/radix_sort.hpp
insert memory fence to avoid AMD OpenCL compiler reordering the read/writes; fixes issue #811
CTest log for Vega56
```
99% tests passed, 2 tests failed out of 169
Total Test time (real) =  85.07 sec
The following tests FAILED:
143 - misc.amd_cpp_kernel_language (Failed)
148 - example.amd_cpp_kernel (Exit code 0xc0000409)
Errors while running CTest
```
> fixes radix sort error

- include/boost/compute/algorithm/detail/scan_on_gpu.hpp
The `local_scan` kernel was accessing the first buffer using the global id without checking if it was within the bounds.
> Fix out of bound access in local_scan kernel

- include/boost/compute/core.hpp
- include/boost/compute/kernel.hpp
- test/test_kernel.cpp
Currently, macOS does not support set_arg with some datatypes. This was partially fixed in #737, but it does not work if the user does not manually specify the `<boost/compute/types.hpp>` header manually.
This PR is expected to fail to build on macOS on the first build. It will then need to be fixed. 
See ddemidov/vexcl#227 for more info.
> Support for set_arg on macOS

- include/boost/compute/algorithm/copy.hpp
- include/boost/compute/algorithm/copy_n.hpp
- include/boost/compute/algorithm/detail/copy_on_device.hpp
- include/boost/compute/algorithm/detail/copy_to_device.hpp
- include/boost/compute/algorithm/detail/copy_to_host.hpp
- include/boost/compute/detail/meta_kernel.hpp
It's not possible to use current "copy" functions with CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE option in command queue, because wait_list parameter is missing.
> Added wait_list parameter to "copy" functions

- test/test_kernel.cpp
On Windows 64 unsigned long has 4 bytes like unsigned int, but it does not seem to be a simple alias for unsigned int. Because of that unsigned long is not OpenCL fundamental type.
> Fix: unsigned long is not fundamental type on Win64

- include/boost/compute/kernel.hpp
- include/boost/compute/memory/local_buffer.hpp
- test/test_kernel.cpp
Per Khronos OpenCL spec:
>If the argument is declared to be a pointer of a built-in scalar or vector type, or a user defined structure type in the global or constant address space, the memory object specified as argument value must be a buffer object (or NULL).
But the following call causes error:
```c++
some_kernel.set_arg(0, NULL);
```
One way as suggested in #828 is to use
```c++
some_kernel.set_arg(0, sizeof(cl_mem), NULL);
```
Now it's just
```c++
some_kernel.set_arg(0, nullptr);
```
> add support to set kernel argument as NULL; fixes issue #828

- doc/reference.qbk
- example/CMakeLists.txt
- include/boost/compute/context.hpp
- include/boost/compute/exception/set_default_queue_error.hpp
- include/boost/compute/system.hpp
- test/CMakeLists.txt
- test/test_attach_user_queue_error.cpp
- test/test_attach_user_queue_thread_safety.cpp
- test/test_system.cpp
By doing so, the associated default device and context will automatically match the user-provided command queue. It
Guarantees unique default queue/device/context is returned when calling from multiple threads (requires config macro BOOST_COMPUTE_THREAD_SAFE)
Resolves issue #827
> Allow manually setting default command queue via `default_queue()`

- include/boost/compute/types/fundamental.hpp
Include static_assert.hpp header in <fundamental.hpp>, required since commit 6c6a1089
> Include Boost's static_assert header in fundamental.hpp

- test/Jamfile.v2
This is necessary to make the tests link under Windows when b2 is used to run them.
> Link to OpenCL under Windows as well in test/Jamfile.v2

- test/test_sha1.cpp
This adds a test for `boost::compute::detail::sha1`, using the test vectors from Wikipedia.
> Add test_sha1.cpp
