.travis.yml
include/boost/compute/algorithm/detail/binary_find.hpp
include/boost/compute/algorithm/detail/copy_on_device.hpp
include/boost/compute/algorithm/detail/inplace_reduce.hpp
include/boost/compute/algorithm/detail/radix_sort.hpp
include/boost/compute/algorithm/detail/reduce_on_gpu.hpp
include/boost/compute/detail/parameter_cache.hpp
include/boost/compute/detail/path.hpp
include/boost/compute/program.hpp
perf/CMakeLists.txt
perf/perf_accumulate.cpp
perf/perf_saxpy.cpp
perf/perf_sort.cpp

This adds a parameter_cache class which can be used to store
execution parameters for an algorithm. Also updates some of
the benchmark programs to find and store optimal parameters.

Add parameter_cache class

---

include/boost/compute/type_traits/is_fundamental.hpp

Add opencl vector types to the list of fundamental types

---

include/boost/compute/detail/vendor.hpp

Apple NVIDIA vendor name does not include Corporation

---

include/boost/compute/command_queue.hpp

This resolves https://github.com/boostorg/compute/issues/365. However, there're two methods that needed workarounds:
1. `clEnqueueBarrier(...)`  in OpenCL 1.0 and 1.1 does not take event argument, so obviously event object cannot be returned in universal `enqueue_barrier(void)` method, but there is already `event enqueue_barrier(const wait_list &events)` method so user can just call it with empty list of events to get event associated with enqueued barrier. 
2. I think that in mapping methods like `enqueue_map_buffer` it's better to return pointer to mapped region like it's now. Therefore, instead of modifying them to return an event object I added event argument to these methods.
I also added missing enqueue_map_image method and asynchronous version of a few other `command_queue` …

Return events from all command_queue::enqueue_* methods

---

include/boost/compute/utility.hpp
include/boost/compute/utility/invoke.hpp
test/CMakeLists.txt
test/test_invoke.cpp

This adds an invoke() function which calls an OpenCL function on a
device with the given arguments.

Add invoke() utility function

---

include/boost/compute/algorithm/detail/find_if_with_atomics.hpp
include/boost/compute/command_queue.hpp

This fixes https://github.com/boostorg/compute/issues/532 and https://github.com/boostorg/compute/issues/530.

Minor fixes

---

test/test_mersenne_twister_engine.cpp

I carelessly inserted tab. This modification replaces it with spaces.

remove bad tab

---

include/boost/compute/utility/wait_list.hpp

This merges #574, #575, and also adds wait-list iterators for completeness.

Wait list improvements

---

include/boost/compute/random/normal_distribution.hpp
test/test_normal_distribution.cpp

Note: this commit includes the changes in PR #590.

Fix normal distribution

---

include/boost/compute/algorithm/adjacent_difference.hpp

Situation where `first == result` was only covered when binary function was not specified.

Fix adjacent_difference when first == result

---

include/boost/compute/interop/opengl/context.hpp

Sorry for the delay, I forgot how to rollback commits :)

Fixed bug in opengl_create_shared_context

---

include/boost/compute/system.hpp

Fix system::platforms()

---

include/boost/compute/algorithm/minmax_element.hpp
test/test_extrema.cpp

Remove useless `Compare` template parameter from `minmax_element()` overload, which was causing errors, and add test for this function.

Fix minmax_element() and add test for it

---

include/boost/compute/algorithm/detail/merge_sort_on_gpu.hpp

Fixes https://github.com/boostorg/compute/issues/669.

Fix merge_sort_on_gpu()

---

include/boost/compute/algorithm/detail/merge_sort_on_gpu.hpp

Fixes bug #688

---

.travis.yml
example/monte_carlo.cpp

Test Boost.Compute using 1.64.

Update Travis CI script

---

include/boost/compute/system.hpp

Optionally enforce device selected with BOOST_COMPUTE_DEFAULT variables

---

include/boost/compute/container/vector.hpp
test/test_vector.cpp

vector::reserve() implemented

---

include/boost/compute/algorithm/detail/scan_on_cpu.hpp

Fix issue #727

---

.travis.yml
include/boost/compute/random/threefry_engine.hpp
include/boost/compute/types/fundamental.hpp
test/test_threefry_engine.cpp

Fix Threefry RNG

---

test/test_device.cpp
test/test_program.cpp

Add runtime checks for OpenCL 2.1 feature tests

---

include/boost/compute/async/future.hpp
test/test_event.cpp

add future::then() method

---

include/boost/compute/iterator/buffer_iterator.hpp
test/test_reduce.cpp

Fix memory leak

---

include/boost/compute/types/fundamental.hpp
test/test_types.cpp

Re-upload of changes from #649 (+ zero-initialisation, let's not introduce new problem for people that rely on that behaviour). I wasn't able to force push to amirshavit's branch after rebasing his changes on `develop`.

Accessors reupload
